export const countries = [
  {
    id: "nepal",
    name: "Nepal",
    tagline: "Master the details of the Himalayan Nation",
    lessons: [
      {
        id: "geo",
        name: "Geography",
        icon: "lucide:mountain",
        color: "bg-emerald-500",
        shadow: "shadow-[0_6px_0_0_rgba(5,150,105,1)]",
        unlocked: true,
      },
      {
        id: "history",
        name: "History",
        icon: "lucide:scroll",
        color: "bg-amber-600",
        shadow: "shadow-[0_6px_0_0_rgba(180,83,9,1)]",
        unlocked: true,
      },
      {
        id: "food",
        name: "Foods",
        icon: "lucide:utensils",
        color: "bg-orange-500",
        shadow: "shadow-[0_6px_0_0_rgba(249,115,22,1)]",
        unlocked: true,
      },
      {
        id: "culture",
        name: "Culture",
        icon: "lucide:users",
        color: "bg-purple-500",
        shadow: "shadow-[0_6px_0_0_rgba(147,51,234,1)]",
        unlocked: false,
      },
      {
        id: "flag",
        name: "The Flag",
        icon: "twemoji:flag-nepal",
        color: "bg-rose-500",
        shadow: "shadow-[0_6px_0_0_rgba(225,29,72,1)]",
        unlocked: false,
      },
      {
        id: "people",
        name: "Personalities",
        icon: "lucide:award",
        color: "bg-blue-500",
        shadow: "shadow-[0_6px_0_0_rgba(59,130,246,1)]",
        unlocked: false,
      },
      {
        id: "politics",
        name: "Politics",
        icon: "lucide:landmark",
        color: "bg-slate-600",
        shadow: "shadow-[0_6px_0_0_rgba(71,85,105,1)]",
        unlocked: false,
      },
      {
        id: "modern",
        name: "Modern Nepal",
        icon: "lucide:smartphone",
        color: "bg-cyan-500",
        shadow: "shadow-[0_6px_0_0_rgba(6,182,212,1)]",
        unlocked: false,
      },
      {
        id: "nature",
        name: "Flora & Fauna",
        icon: "lucide:leaf",
        color: "bg-green-500",
        shadow: "shadow-[0_6px_0_0_rgba(34,197,94,1)]",
        unlocked: false,
      },
      {
        id: "festivals",
        name: "Spirituality",
        icon: "lucide:sparkles",
        color: "bg-pink-500",
        shadow: "shadow-[0_6px_0_0_rgba(236,72,153,1)]",
        unlocked: false,
      },
    ],
  },
  {
    id: "usa",
    name: "USA",
    tagline: "The largest country",
    lessons: [],
  },
  {
    id: "japan",
    name: "Japan",
    tagline: "Land of rising sun",
    lessons: [],
  },
];
